modLoader="javafml"
loaderVersion="[43,)"
license="Custom license"

[[mods]]
modId="fields_of_memory"
version="1.0.0"
displayName="Fields Of Memory"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Robert Angel"

[[dependencies.fields_of_memory]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




