modLoader="javafml"
loaderVersion="[43,)"
license="Custom license"

[[mods]]
modId="fields_of_memory"
version="1.0.0"
displayName="Fields Of Memory"
credits="Robert Angel, Dr. Gannod"
displayURL="https://legacy.curseforge.com/minecraft/mc-mods/fields-of-memory-mod"
authors="Robert Angel"
description='''
Adds music from Fields of Memory
'''

[[dependencies.fields_of_memory]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




